config/routes.rb
Rails.application.routes.draw do
  resources :aliens do
    resources :powers
  end  
  
  root 'welcome#index'
end

app/controllers/aliens_controller.rb
require 'api'
class AliensController < ApplicationController
  TOKEN = 'JjfWKXb23JkJApd9jP3cGg'
  
  def index
    aliens = Alien.new(TOKEN)
    @aliens = aliens.index
  end

  def show
    alien = Alien.new(TOKEN)
    @alien = alien.show(params[:id])
  end

  def new
    alien = Alien.new(TOKEN)
    new_alien = { "name": "Spiderman",
	                "year": 2001,
	                "month": 2,
	                "origin": "earth" }
    @alien = alien.create(new_alien)
    render "new"
  end

  def edit
    alien = Alien.new(TOKEN)
    edit_alien = { "origin": "Mars" }
    @alien = alien.update(params[:id], edit_alien)
    render "edit"
  end

  def destroy
    alien = Alien.new(TOKEN)
    @alien = alien.delete(params[:id])
    render "delete"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/displays_controller.rb
require 'api'
class DisplaysController < ApplicationController
  TOKEN = 'JjfWKXb23JkJApd9jP3cGg'
  
  def index
    aliens = Alien.new(TOKEN)
    @aliens = aliens.index
  end

  def show
    alien = Alien.new(TOKEN)
    @alien = alien.show(params[:id])
  end

  def new
    alien = Alien.new(TOKEN)
    new_alien = { "name": "Spiderman",
	                "year": 2001,
	                "month": 2,
	                "origin": "earth" }
    @alien = alien.create(new_alien)
    render "new"
  end

  def edit
    alien = Alien.new(TOKEN)
    edit_alien = { "origin": "Mars" }
    @alien = alien.update(params[:id], edit_alien)
    render "edit"
  end

  def destroy
    alien = Alien.new(TOKEN)
    @alien = alien.delete(params[:id])
    render "delete"
  end
end

app/controllers/powers_controller.rb
require "api"
class PowersController < ApplicationController
  TOKEN = 'JjfWKXb23JkJApd9jP3cGg'

  def index
    powers = Power.new(TOKEN)
    @powers = powers.index(35)
  end

  def show
    power = Power.new(TOKEN)
    @power = power.show(35, 51)
  end

  def new
    power = Power.new(TOKEN)
    new_power = { "ability": "jump" }
    @power = power.create(35, new_power)
    render "new"
  end

  def edit
    power = Power.new(TOKEN)
    edit_power = { "ability": "Animal Controlled Powers" }
    @power = power.update(35, 51, edit_power)
    render "edit"
  end

  def destroy
    power = Power.new(TOKEN)
    @power = power.delete(35, 72)
    render "delete"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/aliens_helper.rb
module AliensHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/powers_helper.rb
module PowersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/aliens/_response.html.erb
<div>
  <table>
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Year Found</th>
      <th>Month Found</th>
      <th>Origin</th>
    </tr>
    <tr>
      <td><%= alien['id'] %></td>
      <td><%= alien['name'] %></td>
      <td><%= alien['year'] %></td>
      <td><%= alien['month'] %></td>
      <td><%= alien['origin'] %></td>
    </tr>
  </table>
</div>

app/views/aliens/delete.html.erb
<div>
  <h4>Deleted Alien <%= @alien['id'] %></h4>
  <%= render partial: 'response', locals: { alien: @alien } %>
</div>

app/views/aliens/edit.html.erb
<div>
  <h4>Updated Alien <%= @alien['id'] %></h4>
  <%= render partial: 'response', locals: { alien: @alien } %>
</div>

app/views/aliens/index.html.erb
<div>
  <h3>Aliens</h3>
  <h4>Total count: <%= @aliens.count %></h4>
  <table>
    <tr>
      <th>&nbsp;</th>
      <th>Name</th>
      <th>Year Found</th>
      <th>Month Found</th>
      <th>Origin</th>
    </tr>
    <% @aliens.each do |a| %>
    <tr>
      <td><%= a['id'] %></td>
      <td><%= a['name'] %></td>
      <td><%= a['year'] %></td>
      <td><%= a['month'] %></td>
      <td><%= a['origin'] %></td>
    </tr>
    <% end %>
  </table>
</div>

app/views/aliens/new.html.erb
<div>
  <h4>Created Alien <%= @alien['id'] %></h4>
  <%= render partial: 'response', locals: { alien: @alien } %>
</div>

app/views/aliens/show.html.erb
<div>
  <h4>Show Alien <%= @alien['id'] %></h4>
  <%= render partial: 'response', locals: { alien: @alien } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Client</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <ul class="nav nav-tabs">
        <li><%= link_to "Home", root_path %></li>
      </ul>
      <% if flash[:notice] %>
        <div class="alert alert-success">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
      <% elsif flash[:alert] %>
        <div class="alert alert-warning">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:alert] %>
        </div>
      <% end %>
    </div>
    <div class="indent"> 
    
      <%= yield %>
    </div>
  </body>
</html>

app/views/powers/delete.html.erb
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Ability</th>
  </tr>
  <tr>
    <td><%= @power['id'] %></td>
    <td><%= @power['ability'] %></td>
  </tr>
</table>

app/views/powers/edit.html.erb
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Ability</th>
  </tr>
  <tr>
    <td><%= @power['id'] %></td>
    <td><%= @power['ability'] %></td>
  </tr>
</table>

app/views/powers/index.html.erb
<h4>Powers for Alien 35</h4>
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Ability</th>
  </tr>
  <% @powers.each do |p| %>
  <tr>
    <td><%= p['id'] %></td>
    <td><%= p['ability'] %></td>
  </tr>
  <% end %>
</table>
<h4>Power count: <%= @powers.count %></h4>

app/views/powers/new.html.erb
<div>
  <h4>Created Power <%= @power['id'] %></h4>
  <table>
    <tr>
      <th>&nbsp;</th>
      <th>Ability</th>
    </tr>
    <tr>
      <td><%= @power['id'] %></td>
      <td><%= @power['ability'] %></td>
    </tr>
  </table>
</div>

app/views/powers/show.html.erb
<h4>Powers 51 for Alien 35</h4>
<table>
  <tr>
    <th>&nbsp;</th>
    <th>Ability</th>
  </tr>
  <tr>
    <td><%= @power['id'] %></td>
    <td><%= @power['ability'] %></td>
  </tr>
</table>

app/views/welcome/index.html.erb
<div>
  <br />
  <p><%= link_to("All Aliens", aliens_path) %></p>
  
  <p>Alien <input type="text" id="show_id" placeholder="id" size="4" maxlength="4">
  <a onclick="this.href='aliens/' + document.getElementById('show_id').value">show</a></p>

  <p><%= link_to "Create New Alien", new_alien_path %></p>

  <p><%= link_to "Update Alien #1", edit_alien_path(1) %></p>

  <p>Delete Alien <input type="text" id="delete_id" placeholder="id" size="4" maxlength="4">
  <a data-method='delete' data-confirm="Are you sure you want to delete this alien?" onclick="this.href='aliens/' + document.getElementById('delete_id').value">delete</a></p>
  <hr>
  
  <p><%= link_to "Get all Powers for Alien #35", alien_powers_path(35) %></p>

  <p><%= link_to "Show Power #51 for Alien #35", alien_power_path(35, 51) %></p>

  <p><%= link_to "Create New Power for Alien #35", new_alien_power_path(35) %></p>

  <p><%= link_to "Update Power #51 for Alien #35", edit_alien_power_path(35, 17) %></p>

  <p><%= link_to "Delete Power #72 for Alien #35", alien_power_path(35, 72), method: :delete, data: { confirm: 'Are you sure you want to delete this power?' } %></p>
</div>